"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { Activity,ArrowLeft,Flag,FolderPlus,LayoutDashboard,MessageSquare,Pin,ShieldCheck,Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger } from "@/components/ui/alert-dialog";

type Data={stats:{members:number;posts:number;replies:number;reports:number};posts:any[];members:any[];categories:any[];reports:any[]};
export default function AdminDashboard({adminName}:{adminName:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await fetch("/api/admin",{cache:"no-store"});const j=await r.json();if(!r.ok)setError(j.error||"Could not load admin data");else{setData(j);setError("");}},[]);
 useEffect(()=>{void load()},[load]);
 async function action(body:Record<string,unknown>){setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok){const j=await r.json();setError(j.error||"Action failed")}else await load();setBusy(false)}
 async function postAction(id:string,body:Record<string,unknown>){setBusy(true);const r=await fetch(`/api/posts/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)setError("Post update failed");else await load();setBusy(false)}
 if(error&&!data)return <AdminShell name={adminName}><div className="rounded-2xl border border-red-400/30 bg-red-500/10 p-6 text-red-200">{error}</div></AdminShell>;
 if(!data)return <AdminShell name={adminName}><div className="grid gap-4 sm:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl bg-white/5"/>)}</div></AdminShell>;
 const cards=[["Members",data.stats.members,Users],["Discussions",data.stats.posts,MessageSquare],["Replies",data.stats.replies,Activity],["Open reports",data.stats.reports,Flag]] as const;
 return <AdminShell name={adminName}>
  {error&&<div className="mb-5 rounded-xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-400">{label}</span><Icon size={19} className="text-violet-400"/></div><strong className="mt-3 block text-3xl tracking-tight">{value}</strong></div>)}</div>
  <Tabs defaultValue="posts" className="mt-7"><TabsList className="h-auto rounded-xl bg-white/5 p-1"><TabsTrigger value="posts">Posts</TabsTrigger><TabsTrigger value="members">Members</TabsTrigger><TabsTrigger value="categories">Categories</TabsTrigger><TabsTrigger value="reports">Reports</TabsTrigger></TabsList>
   <TabsContent value="posts"><Panel title="Post moderation" description="Pin useful discussions or remove content from the public feed."><AdminTable headings={["Discussion","Author","Status","Replies","Actions"]}>{data.posts.map(p=><tr key={p.id} className="border-t border-white/8"><Cell><span className="font-semibold text-white">{p.title}</span><span className="block text-xs text-slate-500">{p.categoryName}</span></Cell><Cell>{p.authorName}</Cell><Cell><Status value={p.status}/></Cell><Cell>{p.replyCount}</Cell><Cell><div className="flex gap-2"><Button disabled={busy} variant="outline" size="sm" onClick={()=>postAction(p.id,{isPinned:!p.isPinned})}><Pin size={14}/>{p.isPinned?"Unpin":"Pin"}</Button><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive" size="sm">{p.status==="hidden"?"Restore":"Hide"}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{p.status==="hidden"?"Restore":"Hide"} this discussion?</AlertDialogTitle><AlertDialogDescription>This changes whether members can see the discussion in the community feed.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>postAction(p.id,{status:p.status==="hidden"?"published":"hidden"})}>Confirm</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></Cell></tr>)}</AdminTable></Panel></TabsContent>
   <TabsContent value="members"><Panel title="Member management" description="Review member activity and suspend accounts when needed."><AdminTable headings={["Member","Role","Status","Last seen","Actions"]}>{data.members.map(m=><tr key={m.userId} className="border-t border-white/8"><Cell><span className="font-semibold text-white">{m.displayName}</span><span className="block text-xs text-slate-500">{m.email}</span></Cell><Cell>{m.role}</Cell><Cell><Status value={m.status}/></Cell><Cell>{new Date(m.lastSeenAt).toLocaleDateString()}</Cell><Cell>{m.role==="admin"?<span className="text-xs text-slate-500">Protected</span>:<Button disabled={busy} variant="outline" size="sm" onClick={()=>action({action:"memberStatus",id:m.userId,status:m.status==="banned"?"active":"banned"})}>{m.status==="banned"?"Reactivate":"Suspend"}</Button>}</Cell></tr>)}</AdminTable></Panel></TabsContent>
   <TabsContent value="categories"><Panel title="Community categories" description="Create focused spaces for new discussions."><form className="mb-6 grid gap-3 rounded-xl bg-white/[.035] p-4 sm:grid-cols-[1fr_1.5fr_auto]" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({action:"createCategory",name:f.get("name"),description:f.get("description")});e.currentTarget.reset()}}><Input name="name" required placeholder="Category name" className="border-white/10 bg-black/20"/><Input name="description" placeholder="Short description" className="border-white/10 bg-black/20"/><Button disabled={busy} className="bg-violet-600"><FolderPlus size={16}/>Add category</Button></form><AdminTable headings={["Category","Description","State"]}>{data.categories.length?data.categories.map(c=><tr key={c.id} className="border-t border-white/8"><Cell><span className="inline-block h-2.5 w-2.5 rounded-full mr-2" style={{background:c.color}}/>{c.name}</Cell><Cell>{c.description||"—"}</Cell><Cell><Status value={c.isActive?"active":"hidden"}/></Cell></tr>):<tr><td colSpan={3} className="p-8 text-center text-slate-500">No custom categories yet.</td></tr>}</AdminTable></Panel></TabsContent>
   <TabsContent value="reports"><Panel title="Moderation reports" description="Review member-submitted concerns and record a resolution."><AdminTable headings={["Reason","Target","Status","Created","Actions"]}>{data.reports.length?data.reports.map(r=><tr key={r.id} className="border-t border-white/8"><Cell>{r.reason}</Cell><Cell>{r.targetType}</Cell><Cell><Status value={r.status}/></Cell><Cell>{new Date(r.createdAt).toLocaleDateString()}</Cell><Cell>{r.status==="open"?<div className="flex gap-2"><Button size="sm" disabled={busy} onClick={()=>action({action:"reportStatus",id:r.id,status:"resolved"})}>Resolve</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>action({action:"reportStatus",id:r.id,status:"dismissed"})}>Dismiss</Button></div>:<span className="text-xs text-slate-500">Complete</span>}</Cell></tr>):<tr><td colSpan={5} className="p-8 text-center text-slate-500">No reports need attention.</td></tr>}</AdminTable></Panel></TabsContent>
  </Tabs>
 </AdminShell>
}
function AdminShell({name,children}:{name:string;children:React.ReactNode}){return <main className="min-h-screen bg-[#0b0e14] text-white"><header className="border-b border-white/10 bg-[#10141c]"><div className="mx-auto flex h-17 max-w-7xl items-center px-5"><Link href="/" className="mr-5 rounded-lg p-2 text-slate-400 hover:bg-white/5 hover:text-white"><ArrowLeft size={20}/></Link><div className="flex items-center gap-2 font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-600"><ShieldCheck size={19}/></span>Threadline Admin</div><div className="ml-auto text-sm text-slate-400">{name}</div></div></header><div className="mx-auto max-w-7xl px-5 py-7"><div className="mb-6"><div className="flex items-center gap-2 text-sm font-bold text-violet-400"><LayoutDashboard size={16}/>Operations</div><h1 className="mt-1 text-3xl font-extrabold tracking-tight">Community control center</h1></div>{children}</div></main>}
function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="mt-4 overflow-hidden rounded-2xl border border-white/10 bg-white/[.035]"><div className="p-5"><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-slate-400">{description}</p></div><div className="px-5 pb-5">{children}</div></section>}
function AdminTable({headings,children}:{headings:string[];children:React.ReactNode}){return <div className="overflow-x-auto rounded-xl border border-white/8"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-black/20 text-xs uppercase tracking-wider text-slate-500"><tr>{headings.map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="text-slate-300">{children}</tbody></table></div>}
function Cell({children}:{children:React.ReactNode}){return <td className="px-4 py-3.5">{children}</td>}
function Status({value}:{value:string}){const good=["active","published","resolved"].includes(value);return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${good?"bg-emerald-500/10 text-emerald-300":"bg-amber-500/10 text-amber-300"}`}>{value}</span>}
