"use client";
import { useEffect, useMemo, useState } from "react";
import { Bell, Bookmark, ChevronRight, Clock3, Compass, Flame, Heart, Home, Image as ImageIcon, Menu, MessageCircle, MoreHorizontal, Paperclip, Plus, Search, Send, Sparkles, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

const categories = [
  { name:"Introductions", icon:Sparkles, color:"#8b5cf6" }, { name:"General", icon:MessageCircle, color:"#0ea5e9" },
  { name:"Stories", icon:Bookmark, color:"#f97316" }, { name:"Photos & Media", icon:ImageIcon, color:"#ec4899" },
  { name:"Questions", icon:Compass, color:"#10b981" },
];
const discussions = [
 { title:"What’s something small that made your week better?", excerpt:"Let’s collect the little wins. Mine was finding a quiet coffee shop on a rainy morning.", author:"Maya Rivers", initials:"MR", category:"General", time:"8 min", replies:84, likes:219, color:"#0ea5e9", hot:true },
 { title:"A roll of film from my first solo road trip", excerpt:"Twenty-four frames, seven towns, and a lot of beautiful wrong turns. Sharing a few favorites.", author:"Noah Lane", initials:"NL", category:"Photos & Media", time:"26 min", replies:37, likes:156, color:"#ec4899", media:true },
 { title:"How do you stay curious when your routine gets busy?", excerpt:"Looking for practical habits that make room for learning without becoming another obligation.", author:"Elena Park", initials:"EP", category:"Questions", time:"1 hr", replies:61, likes:93, color:"#10b981" },
 { title:"The neighbor who taught our whole block to garden", excerpt:"A story about shared tomatoes, borrowed tools, and the unexpected community at the end of our street.", author:"Marcus Reed", initials:"MR", category:"Stories", time:"2 hr", replies:29, likes:188, color:"#f97316" },
];
const trending = ["#weekendprojects","#photostories","#goodquestions","#firstpost"];

export default function HomePage(){
 const [active,setActive]=useState("Home"), [filter,setFilter]=useState("Latest"), [query,setQuery]=useState(""), [menuOpen,setMenuOpen]=useState(false);
 const [liked,setLiked]=useState<number[]>([1]), [saved,setSaved]=useState<number[]>([]), [posted,setPosted]=useState(false);
 const [livePosts,setLivePosts]=useState<any[]>([]),[postError,setPostError]=useState("");
 useEffect(()=>{fetch("/api/posts",{cache:"no-store"}).then(r=>r.json()).then(j=>setLivePosts((j.posts||[]).map((p:any)=>({id:p.id,title:p.title,excerpt:p.body,author:p.authorName,initials:p.authorName.split(/\s+/).map((x:string)=>x[0]).join("").slice(0,2).toUpperCase(),category:p.categoryName,time:new Date(p.createdAt).toLocaleDateString(),replies:p.replyCount,likes:p.likeCount,color:"#6257e8",hot:p.isPinned})))).catch(()=>{})},[posted]);
 const visible=useMemo(()=>[...livePosts,...discussions].filter(d=>(active==="Home"||active==="Explore"||d.category===active)&&(d.title+d.excerpt+d.author).toLowerCase().includes(query.toLowerCase())),[active,query,livePosts]);
 async function createDiscussion(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setPostError("");const form=e.currentTarget,f=new FormData(form),r=await fetch("/api/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:f.get("title"),body:f.get("body"),category:f.get("category")})}),j=await r.json();if(!r.ok){setPostError(j.error||"Could not publish this discussion.");return}form.reset();setPosted(true)}
 return <main className="min-h-screen bg-[#f7f8fb] text-[#172033]">
  <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/92 backdrop-blur-xl"><div className="mx-auto flex h-17 max-w-[1440px] items-center gap-4 px-4 sm:px-6 lg:px-10">
   <button className="rounded-xl p-2 lg:hidden" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Menu size={22}/></button>
   <button onClick={()=>setActive("Home")} className="flex shrink-0 items-center gap-2.5" aria-label="Threadline home"><span className="grid h-9 w-9 place-items-center rounded-[11px] bg-[#6257e8] text-white shadow-[0_8px_20px_rgba(98,87,232,.28)]"><MessageCircle size={20} fill="currentColor"/></span><span className="text-[19px] font-extrabold tracking-[-.04em]">threadline</span></button>
   <div className="relative mx-auto hidden w-full max-w-[520px] md:block"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 rounded-full border-slate-200 bg-slate-100/80 pl-10 shadow-none focus-visible:ring-[#6257e8]" placeholder="Search discussions, topics, and members"/></div>
   <div className="ml-auto flex items-center gap-2"><button className="relative grid h-10 w-10 place-items-center rounded-full text-slate-600 hover:bg-slate-100" aria-label="Notifications"><Bell size={20}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full border-2 border-white bg-[#f05252]"/></button>
    <Dialog><DialogTrigger asChild><Button className="h-10 rounded-full bg-[#6257e8] px-4 font-bold hover:bg-[#5146d6]"><Plus size={18}/><span className="hidden sm:inline">New discussion</span></Button></DialogTrigger><DialogContent className="rounded-3xl sm:max-w-[560px]"><DialogHeader><DialogTitle className="text-2xl">Start a discussion</DialogTitle><DialogDescription>Share a story, ask a question, or start a conversation.</DialogDescription></DialogHeader>
     {posted?<div className="rounded-2xl bg-emerald-50 p-6 text-center"><div className="mx-auto mb-3 grid h-11 w-11 place-items-center rounded-full bg-emerald-500 text-white"><Send size={19}/></div><h3 className="font-bold">Your discussion is live</h3><p className="mt-1 text-sm text-emerald-800">The community can now join the conversation.</p><button onClick={()=>setPosted(false)} className="mt-3 text-sm font-bold text-emerald-700">Post another</button></div>:<form className="space-y-4" onSubmit={createDiscussion}><Input name="title" required placeholder="Discussion title" className="h-12 rounded-xl"/><select name="category" className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option>General</option><option>Introductions</option><option>Stories</option><option>Photos &amp; Media</option><option>Questions</option></select><textarea name="body" required className="min-h-36 w-full resize-none rounded-xl border border-slate-200 p-3 outline-none focus:ring-2 focus:ring-[#6257e8]" placeholder="What’s on your mind?"/>{postError&&<p className="text-sm font-semibold text-red-600">{postError}</p>}<div className="flex items-center justify-between"><button type="button" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><Paperclip size={17}/>Add media</button><Button type="submit" className="rounded-full bg-[#6257e8] px-5">Post discussion</Button></div></form>}
    </DialogContent></Dialog><button onClick={()=>location.assign("/admin")} className="ml-1 grid h-10 w-10 place-items-center rounded-full bg-[#1f2b45] text-sm font-extrabold text-white" aria-label="Open administration">DE</button>
   </div>
  </div></header>
  <div className="mx-auto grid max-w-[1440px] grid-cols-1 gap-7 px-4 py-6 sm:px-6 lg:grid-cols-[220px_minmax(0,1fr)_280px] lg:px-10">
   <aside className={`${menuOpen?"block":"hidden"} lg:block`}><nav className="sticky top-24 space-y-1">
    {[{name:"Home",icon:Home},{name:"Explore",icon:Compass},{name:"Following",icon:Users}].map(({name,icon:Icon})=><button key={name} onClick={()=>{setActive(name);setMenuOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left font-semibold ${active===name?"bg-[#eceafd] text-[#5549dc]":"text-slate-600 hover:bg-white"}`}><Icon size={19}/>{name}</button>)}
    <p className="px-3 pb-2 pt-6 text-xs font-extrabold uppercase tracking-[.12em] text-slate-400">Communities</p>
    {categories.map(({name,icon:Icon,color})=><button key={name} onClick={()=>{setActive(name);setMenuOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold ${active===name?"bg-white shadow-sm":"text-slate-600 hover:bg-white"}`}><span className="grid h-7 w-7 place-items-center rounded-lg text-white" style={{background:color}}><Icon size={15}/></span>{name}</button>)}
    <div className="mt-7 rounded-2xl bg-[#172033] p-4 text-white"><p className="text-sm font-bold">Make this place yours</p><p className="mt-1 text-xs leading-5 text-slate-300">Follow topics and meet people who care about the same things.</p><button className="mt-3 text-xs font-bold text-[#aca6ff]">Browse communities →</button></div>
   </nav></aside>
   <section className="min-w-0"><div className="mb-5 flex items-end justify-between gap-3"><div><p className="mb-1 text-sm font-semibold text-[#6257e8]">Good afternoon, Dwayne</p><h1 className="text-3xl font-extrabold tracking-[-.04em]">{active==="Home"?"Your community feed":active}</h1></div><button className="rounded-xl p-2 text-slate-400 hover:bg-white"><MoreHorizontal/></button></div>
    <div className="relative mb-4 md:hidden"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 rounded-full bg-white pl-10" placeholder="Search discussions"/>{query&&<button onClick={()=>setQuery("")} className="absolute right-3 top-3"><X size={18}/></button>}</div>
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{["Latest","Popular","Unanswered"].map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-full px-4 py-2 text-sm font-bold ${filter===item?"bg-[#172033] text-white":"bg-white text-slate-500 hover:text-slate-900"}`}>{item}</button>)}</div>
    <div className="space-y-3">{visible.map((d,index)=><article key={d.title} className="group rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_2px_10px_rgba(15,23,42,.025)] transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-[0_12px_34px_rgba(44,45,90,.08)] sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-xs font-extrabold text-white" style={{background:d.color}}>{d.initials}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-slate-400"><span className="font-bold text-slate-700">{d.author}</span><span>in</span><span className="font-semibold" style={{color:d.color}}>{d.category}</span><span>·</span><span>{d.time} ago</span>{d.hot&&<span className="ml-auto flex items-center gap-1 rounded-full bg-orange-50 px-2 py-1 font-bold text-orange-600"><Flame size={13} fill="currentColor"/>Trending</span>}</div><h2 onClick={()=>d.id&&location.assign(`/thread/${d.id}`)} className="mt-2 cursor-pointer text-[19px] font-extrabold leading-snug tracking-[-.02em] group-hover:text-[#5549dc]">{d.title}</h2><p className="mt-2 line-clamp-2 leading-6 text-slate-500">{d.excerpt}</p>
     {d.media&&<div className="mt-4 grid h-38 grid-cols-3 gap-1.5 overflow-hidden rounded-xl"><div className="col-span-2 bg-[linear-gradient(145deg,#6e85a4,#d9a779_55%,#48536a)]"/><div className="grid grid-rows-2 gap-1.5"><div className="bg-[linear-gradient(135deg,#d17d62,#4e6672)]"/><div className="relative bg-[linear-gradient(135deg,#6a8f72,#d5bd7d)]"><span className="absolute inset-0 grid place-items-center bg-black/25 text-sm font-bold text-white">+8</span></div></div></div>}
     <div className="mt-4 flex items-center gap-5 border-t border-slate-100 pt-4 text-sm font-semibold text-slate-400"><button onClick={()=>setLiked(v=>v.includes(index)?v.filter(x=>x!==index):[...v,index])} className={`flex items-center gap-1.5 hover:text-rose-500 ${liked.includes(index)?"text-rose-500":""}`}><Heart size={17} fill={liked.includes(index)?"currentColor":"none"}/>{d.likes+(liked.includes(index)?1:0)}</button><button className="flex items-center gap-1.5 hover:text-[#6257e8]"><MessageCircle size={17}/>{d.replies}</button><button onClick={()=>setSaved(v=>v.includes(index)?v.filter(x=>x!==index):[...v,index])} className={`ml-auto hover:text-[#6257e8] ${saved.includes(index)?"text-[#6257e8]":""}`} aria-label="Save discussion"><Bookmark size={18} fill={saved.includes(index)?"currentColor":"none"}/></button></div>
    </div></div></article>)}{visible.length===0&&<div className="rounded-2xl bg-white p-12 text-center"><Search className="mx-auto text-slate-300" size={32}/><h2 className="mt-3 font-bold">No discussions found</h2><p className="mt-1 text-sm text-slate-500">Try a different search or community.</p></div>}</div>
   </section>
   <aside className="hidden xl:block"><div className="sticky top-24 space-y-5"><section className="rounded-2xl border border-slate-200/80 bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-extrabold">Popular topics</h2><ChevronRight size={18} className="text-slate-400"/></div><div className="space-y-4">{trending.map((tag,i)=><button key={tag} className="flex w-full items-center gap-3 text-left"><span className="text-lg font-black text-slate-200">0{i+1}</span><span><span className="block text-sm font-bold text-slate-700">{tag}</span><span className="text-xs text-slate-400">{[142,96,81,64][i]} conversations</span></span></button>)}</div></section>
    <section className="rounded-2xl border border-slate-200/80 bg-white p-5"><h2 className="mb-4 font-extrabold">Active now</h2><div className="mb-4 flex -space-x-2">{["AM","JK","TS","LB","+9"].map((x,i)=><span key={x} className="grid h-9 w-9 place-items-center rounded-full border-2 border-white text-[10px] font-extrabold text-white" style={{background:["#6257e8","#0ea5e9","#f97316","#10b981","#172033"][i]}}>{x}</span>)}</div><p className="text-sm leading-6 text-slate-500"><span className="font-bold text-slate-700">38 members</span> are reading and replying right now.</p></section>
    <section className="rounded-2xl bg-[#eceafd] p-5"><div className="mb-3 flex items-center gap-2 text-[#5549dc]"><Clock3 size={18}/><span className="text-xs font-extrabold uppercase tracking-wider">Community note</span></div><p className="text-sm font-bold leading-6 text-[#373174]">Be curious, be kind, and make room for every voice.</p></section>
   </div></aside>
  </div>
 </main>
}
