"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft,Flag,MessageCircle,Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
type Thread={post:any;replies:any[]};
export default function ThreadView({id}:{id:string}){const [data,setData]=useState<Thread|null>(null),[error,setError]=useState(""),[sent,setSent]=useState(false);const load=useCallback(()=>fetch(`/api/posts/${id}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message)),[id]);useEffect(()=>{void load()},[load]);async function reply(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),r=await fetch(`/api/posts/${id}/replies`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:f.get("body")})});const j=await r.json();if(!r.ok){setError(j.error);return}form.reset();setSent(true);await load()}async function report(reason:string){await fetch("/api/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetType:"post",targetId:id,reason})})}
return <main className="min-h-screen bg-[#f7f8fb] text-[#172033]"><header className="border-b bg-white"><div className="mx-auto flex h-17 max-w-4xl items-center px-5"><Link href="/" className="flex items-center gap-2 font-bold text-slate-600"><ArrowLeft size={18}/>Back to discussions</Link><span className="ml-auto font-extrabold text-[#6257e8]">threadline</span></div></header><div className="mx-auto max-w-4xl px-5 py-8">{error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{!data&&!error&&<div className="h-56 animate-pulse rounded-2xl bg-white"/>}{data&&<><article className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><div className="text-sm font-bold text-[#6257e8]">{data.post.categoryName}</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight">{data.post.title}</h1><div className="mt-3 text-sm text-slate-400">Posted by <span className="font-bold text-slate-700">{data.post.authorName}</span> · {new Date(data.post.createdAt).toLocaleString()}</div><p className="mt-6 whitespace-pre-wrap text-lg leading-8 text-slate-600">{data.post.body}</p><div className="mt-6 flex items-center border-t pt-4 text-sm text-slate-500"><MessageCircle size={17} className="mr-2"/>{data.replies.length} replies<Dialog><DialogTrigger asChild><button className="ml-auto flex items-center gap-1.5 font-semibold hover:text-red-600"><Flag size={15}/>Report</button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Report discussion</DialogTitle><DialogDescription>Tell the moderators what needs attention.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void report(String(f.get("reason")));e.currentTarget.reset()}}><textarea name="reason" required className="min-h-28 w-full rounded-xl border p-3" placeholder="Reason for reporting"/><Button type="submit" className="mt-3">Submit report</Button></form></DialogContent></Dialog></div></article><section className="mt-6 space-y-3"><h2 className="text-xl font-extrabold">Replies</h2>{data.replies.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="text-sm font-bold">{r.authorName}<span className="ml-2 font-normal text-slate-400">{new Date(r.createdAt).toLocaleString()}</span></div><p className="mt-3 whitespace-pre-wrap leading-7 text-slate-600">{r.body}</p></article>)}{!data.replies.length&&<p className="rounded-2xl bg-white p-6 text-slate-500">No replies yet. Start the conversation.</p>}<form onSubmit={reply} className="rounded-2xl border border-slate-200 bg-white p-5"><label className="mb-2 block font-bold">Add a reply</label><textarea name="body" required className="min-h-28 w-full rounded-xl border p-3" placeholder="Write a thoughtful response…"/>{sent&&<p className="mt-2 text-sm font-semibold text-emerald-600">Reply posted.</p>}<Button type="submit" className="mt-3 rounded-full bg-[#6257e8]"><Send size={16}/>Post reply</Button></form></section></>}</div></main>}
